export const formattedChapters = {
  "after": "Married Life",
  "amesSisters": "The Ames Sisters",
  "auditions": "One or the other",
  "fitModel": "Costume Model",
  "graduation": "Graduates High School",
  "marieAndJoe": "Marie and Joe",
  "marvelettes": "The Marvelettes",
  "millerSisters": "Miller Sisters Dance Studio",
  "nedWayburn": "Ned Wayburn's School",
  "pathToTheRoxy": "Path to the Roxy",
  "training": "First Stop: DC",
  "tracySisters": "Tracy Sisters Studio",
  "retirement": "Early Retirement",
  "roxyette": "Life at the Roxy",
  "roxySwanSong": "Swan Song for the Roxy",
  "southAmerica": "'No' to South America",
  "tracys": "The Tracys",
  "wedding": "Wedding Bells",
}